from_latest_tag = false
ignore_merge_commits = false
disable_changelog = true
generate_mono_repository_global_tag = true
branch_whitelist = ['main']
skip_ci = "[skip ci]"
skip_untracked = true
pre_bump_hooks = []
post_bump_hooks = [
    "git tag -f v{{version.major}} v{{version}}",
    "git tag -f v{{version.major}}.{{version.minor}} v{{version}}",
    "git push",
    "git push --tags -f",
]

pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"
disable_bump_commit = true

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
